version: "3"
services:
  db:
    image: ishay6411/investor_pro_postgres_db:v1
    environment:
      - POSTGRES_USER=InvestorPro
      - POSTGRES_PASSWORD=123456!@
      - POSTGRES_DB=AppDataBase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: